### ISSUE TITLE
Incorrect git link

### ISSUE THREAD

**Issue by ankursah5** [yalamanchilivahini5/vsdtclpowertool#1]
Hi Vahini,
The git link under the section "tcl power usage" seems to be incorrect. can you please rectify that?

**Comment by yalamanchilivahini5** [comment]
Hi Ankur,
Sorry for inconvenience
The git link is updated. You can check it and might close the issue.

**Comment by ankursah5** [comment]
Okay.
This looks good.
Closing the issue.
