### ISSUE TITLE
messaging in tcl power usage 

### ISSUE THREAD

**Issue by ankursah5** [yalamanchilivahini5/vsdtclpowertool#2]
Hi Vahini,
can you please correct the messaging under the tcl power usage section, step 3? I think it should be "copy the design in ngspice folder".

**Comment by yalamanchilivahini5** [comment]
Hi Ankur,

Can you review changed steps? If it is good you might want to close the issue.

**Comment by ankursah5** [comment]
Hi Vahini,
Now the steps have clear instructions. Closing this issue.
