### ISSUE TITLE
Regarding circuit modifications

### ISSUE THREAD

**Issue by ankursah5** [yalamanchilivahini5/vsdtclpowertool#3]
Hi Vahini,
I think the image for circuit modifications should come after step 3). Kindly have a look at it.

**Comment by yalamanchilivahini5** [comment]
Hi Ankur, 

I did the changes in steps. If it convenient now you might want to close the issue.

**Comment by ankursah5** [comment]
Hi Vahini,
Now the steps are clear. Closing this issue.
