### ISSUE TITLE
Regarding time varying inputs

### ISSUE THREAD

**Issue by ankursah5** [yalamanchilivahini5/vsdtclpowertool#4]
Hi Vahini,
Can you improve the messaging for time varying inputs? currently its not clear. I was able to run leakage but got confused with the messaging. 
Good Job.

**Comment by yalamanchilivahini5** [comment]
Hi ankur,
Sorry for  inconvenience.
I have improved the messaging part for time varying inputs. Can you review it once? If it  clears your confusion you might close the issue.

Thanks.

**Comment by ankursah5** [comment]
hello Vahini,
Now it looks good. closing the issue now.
