### ISSUE TITLE
Leakage power in uW

### ISSUE THREAD

**Issue by ankursah5** [yalamanchilivahini5/vsdtclpowertool#5]
Hi Vahini,
I think its a good idea to report the power in uW directly.

**Comment by yalamanchilivahini5** [comment]
Hi Ankur,

Thanks for suggestion.
I have modified and reported the power in both W and uW. 

You can have a look at it. If it seems good you might close this issue.

**Comment by ankursah5** [comment]
Yeah it looks good now.
