### ISSUE TITLE
Netlist with subcircuits

### ISSUE THREAD

**Issue by VSD-DACteam** [yalamanchilivahini5/vsdtclpowertool#6]
Hi Vahini,
My netlist contains subcircuits. Will your powertool work for the same. Kunal asked to check with you.
The netlist is upload in the below mentioned github repository with the name "10bitdac.cir"
https://github.com/VSD-DACteam/avsddac_3v3
Thankyou

**Comment by yalamanchilivahini5** [comment]
Hi,
It also works for subcircuits. You can check it once. But i couldn't find your netlist file with name "10bitdac.cir" to check it.

If it works then you can close the issue.

**Comment by yalamanchilivahini5** [comment]
Hi DACteam,
I checked leakage power for your circuit. The powertool is working good. You can even check for switching power also. 

If it works fine you can close the issue.
